// F3.5.5C — QUANTIDADE PERSONALIZADA DE ROTEIROS + EDITOR RICO (Desktop 1.0.224): suíte estática.
// A) versão · B) 35 testes obrigatórios da QUANTIDADE · C) 50 testes obrigatórios do EDITOR ·
// D) segurança · E) Worker (portal) · F) congelados/isolamento.
// Roda contra o fonte real (ou SRC= p/ gate empacotado). O Worker é lido do repo (WSRC= opcional).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FILE = process.env.SRC ? path.resolve(process.env.SRC) : path.resolve(__dirname, '..', 'src', 'renderer', 'index.html');
const S = fs.readFileSync(FILE, 'utf8');
const WFILE = process.env.WSRC ? path.resolve(process.env.WSRC) : path.resolve(__dirname, '..', '..', 'cloudflare-worker.js');
const W = fs.readFileSync(WFILE, 'utf8');
const R = f => fs.readFileSync(path.resolve(__dirname, '..', f), 'utf8');
let n = 0, fails = 0;
function ok(label, cond) { n++; if (cond) { console.log('  ✓ ' + label); } else { fails++; console.log('  ✗ FALHOU: ' + label); } }
function segOf(SRC, a, b, name) {
  const i = SRC.indexOf(a); const j = SRC.indexOf(b, i + a.length);
  if (i < 0 || j < 0) { console.log('  ✗ ÂNCORA AUSENTE (' + name + '): ' + (i < 0 ? a : b)); fails++; n++; return ''; }
  return SRC.slice(i, j);
}
const seg = (a, b, name) => segOf(S, a, b, name);
const wseg = (a, b, name) => segOf(W, a, b, name);
const has = (h, s) => h.indexOf(s) >= 0;
const count = (h, s) => h.split(s).length - 1;

const qcore = seg('/* ══ F3.5.5C — ROTEIRO: QUANTIDADE PERSONALIZADA', 'function curSub(){', 'qcore');
const cursub = seg('function curSub(){', 'function stepSector(){', 'curSub');
const brief = seg('function stepBriefing(){', 'function stepReview(){', 'briefing');
const review = seg('function stepReview(){', 'function canSendToClient(f){', 'review');
const after = seg('function afterForm(){', 'function composedDesc(){', 'afterForm');
const savet = seg('async function saveTask(){', 'async function saveCardsBatch(){', 'saveTask');
const disp = seg("if(el=g('[data-sqplus]'))", "if(el=g('[data-content]'))", 'dispatcher-quantidade');
const rte = seg('/* ════════════════ F3.5.5C — EDITOR RICO DE TEMAS E LEGENDAS (RTE)', 'function newForm(sector){', 'rte-core');
const sanit = seg('function rteSanitize(html){', 'function richToPlain(html){', 'sanitize');
const proj = seg('function richToPlain(html){', 'function plainToRich(text){', 'projeção');
const wire = seg('function _rteWireGlobal(){', 'try{_rteWireGlobal();}catch(_e){}', 'wire');
// RE-PINADO F3.5.5D: o corpo da colagem do RTE virou _rtePasteApply (mesmo pipeline sanitizado),
// reutilizado pelo evento nativo E pelo fallback determinístico Ctrl+V/Shift+Insert via IPC.
const pasteApply = seg('function _rtePasteApply(ed,htmlD,txt){', 'function newForm(sector){', 'pasteApply');
const ce = seg('function openContentEditor(taskId){', '/* ===== PRODUÇÃO DO CONTEÚDO', 'content-editor');
const fixo = seg('function openItemFix(taskId,idx,field){', 'function detFooter(t,cron){', 'item-fix');
const prod = seg('function openProductionModal(taskId){', 'async function saveProduction(taskId,resend){', 'produção');
const det = seg('  if(cron){\n    var _word=detItemWord(t);', "  }else if(String(t.sector||'')==='edicao_cards'){", 'central-detalhes');
const copyd = seg("if(el=g('[data-detcopytheme],[data-detcopycaption]'))", "if(el=g('[data-tab]'))", 'copy-dispatcher');
const wrte = wseg('/* ═══ F3.5.5C — TEMA/LEGENDA RICOS NO PORTAL', 'function frequencyLabel', 'worker-rte');
const wrender = wseg('contentsHtml = items.map(function (raw, i) {', 'histórico granular', 'worker-render');
const wstate = wseg('async function handleClientCronogramaState(token, env)', 'Persistência ADITIVA e granular', 'worker-state');

console.log('— A) versão 1.0.224 —');
const pkg = JSON.parse(R('package.json'));
ok('A1 package.json 1.0.224 (custom-script-quantity-rich-editor)', pkg.version === '1.0.224' && /custom-script-quantity-rich-editor/.test(pkg.description || ''));
ok('A2 package-lock 1.0.224', JSON.parse(R('package-lock.json')).version === '1.0.224');
ok('A3 lock packages[""] 1.0.224', JSON.parse(R('package-lock.json')).packages[''].version === '1.0.224');

console.log('— B) QUANTIDADE PERSONALIZADA DE ROTEIROS (35 obrigatórios) —');
ok('B1 quantidade 1: subtipo sintético aceita n=1 com singular ("1 roteiro")', has(qcore, "return {label:n+(n===1?' roteiro':' roteiros')") && has(qcore, 'if(!(isFinite(n)&&n>=1))return null;'));
ok('B2 quantidade 2: contentCount:n dirige os blocos (mesmo contrato dos chips)', has(qcore, 'contentCount:n,fields:[]'));
ok('B3 quantidade 3: normScriptQty devolve o inteiro digitado (sem arredondar p/ opções fixas)', has(qcore, 'var n=Math.floor(Number(s));') && has(qcore, 'return n;'));
ok('B4 quantidade 4: compat q4 no fallback legado', has(qcore, 'var m={q4:4,q6:6,q8:8,q12:12};'));
ok('B5 quantidade 6: placeholder de exemplo "Ex.: 6" (sem default forçado 4)', has(brief, 'placeholder="Ex.: 6"') && !has(brief, "scriptQty||4"));
ok('B6 quantidade 8: fallback legado q8 preservado', has(qcore, 'q8:8'));
ok('B7 quantidade 12: fallback legado q12 preservado', has(qcore, 'q12:12'));
ok('B8 quantidade 13: livre — teto técnico único é SCRIPT_QTY_MAX', has(S, 'var SCRIPT_QTY_MAX=500;') && has(qcore, 'if(n>SCRIPT_QTY_MAX)'));
ok('B9 quantidade 20: idem (nenhuma lista fixa no caminho novo do commit)', !has(qcore, '[4,6,8,12]'));
ok('B10 quantidade 50: idem; aviso claro só acima do teto', has(qcore, "flashToast('Quantidade máxima por tarefa: '+SCRIPT_QTY_MAX+' roteiros"));
ok('B11 digitação direta: oninput guarda rascunho SEM re-render (não perde foco)', has(after, "bind('#fScriptQty',e=>{state.form.scriptQty=e.value;});"));
ok('B12 botão aumentar: [+] parte do valor atual e commita +1', has(disp, "scriptQtyCommit(_sqb+1);return;"));
ok('B13 botão diminuir: [−] só reduz acima de 1 (nunca abaixo do mínimo)', has(disp, "if(_sqc>1)scriptQtyCommit(_sqc-1);return;"));
ok('B14 setas do teclado: input type=number step=1 min=1 (setas nativas) + onchange commita', has(brief, 'type="number" min="1" step="1" inputmode="numeric"') && has(after, "_sqEl.onchange=function(ev){scriptQtyCommit("));
ok('B15 colagem: commit normaliza String(raw).trim() + floor (colar "12" funciona)', has(qcore, "var s=String(raw==null?'':raw).trim();"));
ok('B16 zero: rejeitado com mensagem visível (não corrige em silêncio)', has(qcore, "f._sqErr=(raw!==''&&!(/^\\d+$/.test(raw)&&Number(raw)>=1));") && has(brief, 'Informe uma quantidade inteira igual ou superior a 1.'));
ok('B17 negativo: mesmo gate (mensagem) + normalização mínima 1', has(qcore, 'if(n<1)return 1;'));
ok('B18 decimal: piso inteiro + mensagem de inválido (regex só dígitos)', has(qcore, 'Math.floor(Number(s))') && has(qcore, '/^\\d+$/'));
ok('B19 letras: viram vazio (isFinite) + mensagem', has(qcore, "if(!isFinite(n))return '';"));
ok('B20 campo vazio: permanece OPCIONAL (semântica dos chips preservada; sem erro)', has(qcore, "if(s==='')return '';") && has(qcore, 'o campo era e PERMANECE opcional'));
ok('B21 aumentar preserva: truncagem só quando contents.length>newN (crescer nunca toca itens)', has(qcore, 'if(newN!==null&&Array.isArray(f.contents)&&f.contents.length>newN)f.contents.length=newN;'));
ok('B22 diminuir vazios: excedente sem conteúdo corta direto (extra==0 não abre modal)', has(qcore, 'if(newN!==null&&newN<prevN&&extra>0){ f._sqPend=newN; openScriptShrinkConfirm(extra,prevN,newN); return; }'));
ok('B23 diminuir preenchidos: detecta tema/legenda/RICO no excedente', has(qcore, "(c.tema&&String(c.tema).trim())||(c.legenda&&String(c.legenda).trim())||c.temaRich||c.legendaRich"));
ok('B24 confirmação de remoção: modal claro (N excedentes removidos; 1..newN intactos)', has(qcore, 'serão <b style="color:#F87171">removidos</b>') && has(qcore, 'permanecem exatamente como estão'));
ok('B25 cancelar remoção: mantém TODOS os dados (só limpa a pendência)', has(disp, "if(el=g('[data-sqshrinkcancel]')){var _f2=state.form;if(_f2){delete _f2._sqPend;}closeModal();render();return;}"));
ok('B26 avançar: navegação de etapas não zera contents (reset só em troca de setor/subtipo)', has(S, "if(el=g('[data-fsector]')){state.form.sector=el.dataset.fsector;state.form.subtype=null;state.form.contents=[];") && !has(S, "formgoto']\")){state.form.contents=[]"));
ok('B27 voltar: idem — dispatcher de goto não toca contents', !/data-formgoto[^\n]*contents\s*=/.test(S));
ok('B28 revisão: rótulo "Quantidade de roteiros" + contagem real', has(review, "secOf(f.sector).key==='roteiro'?'Quantidade de roteiros':'Subtipo'"));
ok('B29 salvar: compactação preserva o OBJETO inteiro do item (rich viaja junto)', has(savet, "var _cc=(Array.isArray(f.contents)?f.contents:[]).filter(function(c){return c&&(c.tema||c.legenda);}); if(_cc.length)data.cronContents=_cc;"));
ok('B30 reabrir: fallback SÓ em edição (f.id) usa tamanho REAL do array', has(qcore, 'if(f.id){') && has(qcore, 'if(Array.isArray(f.contents)&&f.contents.length)return Math.min(f.contents.length,SCRIPT_QTY_MAX);'));
ok('B31 tarefa antiga 4: q4→4 sem migração', has(qcore, 'q4:4'));
ok('B32 tarefa antiga 6: q6→6 sem migração', has(qcore, 'q6:6'));
ok('B33 tarefa antiga 8: TEMPLATES.roteiro.subtypes preservado p/ leitura legada', has(S, "roteiro:{titleLabel:'Título do roteiro'"));
ok('B34 tarefa antiga 12: nenhuma reescrita ao abrir (fallback é só leitura)', has(qcore, 'sem migração'));
ok('B35 sem perda de dados: curSub() do roteiro é dirigido pelo N (pipeline idêntico a jusante)', has(cursub, "if(secOf(state.form.sector).key==='roteiro')return synthScriptSub(scriptQtyOf(state.form));"));

console.log('— C) EDITOR RICO DE TEMA/LEGENDA (50 obrigatórios) —');
ok('C1 texto simples: sem formatação NÃO grava campo rico (doc byte-equivalente ao legado)', has(rte, "o[field]=plain; if(hasFmt)o[field+'Rich']=rich; else delete o[field+'Rich'];"));
ok('C2 negrito: b/strong→<strong> + botão + Ctrl+B', has(sanit, "if(tg==='B'||tg==='STRONG')return innerH?stWrap('<strong>'+innerH+'</strong>'):'';") && has(rte, "_rteBtn('bold','Negrito (Ctrl+B)'") && has(wire, "if(k==='b'){ev.preventDefault();ev.stopPropagation();_rteExec(ed,'bold');return;}"));
ok('C3 itálico: i/em→<em> + botão + Ctrl+I', has(sanit, "if(tg==='I'||tg==='EM')return innerH?stWrap('<em>'+innerH+'</em>'):'';") && has(wire, "if(k==='i')"));
ok('C4 sublinhado: u→<u> + Ctrl+U', has(sanit, "if(tg==='U')return innerH?stWrap('<u>'+innerH+'</u>'):'';") && has(wire, "if(k==='u')"));
ok('C5 tachado: s/strike/del→<s>', has(sanit, "if(tg==='S'||tg==='STRIKE'||tg==='DEL')return innerH?stWrap('<s>'+innerH+'</s>'):'';"));
ok('C6 subscrito: sub + botão', has(sanit, "if(tg==='SUB')") && has(rte, "_rteBtn('sub','Subscrito'"));
ok('C7 sobrescrito: sup + botão', has(sanit, "if(tg==='SUP')") && has(rte, "_rteBtn('sup','Sobrescrito'"));
ok('C8 cor: paleta FECHADA de 8 (data-cl 1..8; fora da paleta descarta mantendo texto)', has(rte, "var RTE_COLORS=['#F87171','#FB923C','#FACC15','#34D399','#22D3EE','#60A5FA','#A78BFA','#F472B6'];") && has(sanit, "(dcl&&/^[1-8]$/.test(dcl))?dcl:(_RTE_COLOR_BY_RGB[stC]||'')"));
ok('C9 marca-texto: paleta FECHADA de 6 (data-hl 1..6)', has(rte, "var RTE_HL=['#FEF08A','#BBF7D0','#BAE6FD','#FBCFE8','#FDBA74','#E9D5FF'];") && has(sanit, "(dhl&&/^[1-6]$/.test(dhl))?dhl:(_RTE_HL_BY_RGB[stB]||'')"));
ok('C10 lista com marcadores: ul canônica + botão', has(sanit, "if(tg==='UL'||tg==='OL'){") && has(rte, "_rteBtn('ul','Lista com marcadores'"));
ok('C11 lista numerada: ol + botão', has(rte, "_rteBtn('ol','Lista numerada'"));
ok('C12 alinhar esquerda: text-align:left LIMPA data-al antigo (gesto vivo tem precedência)', has(rte, "if(s==='left'||s==='start')return '';"));
ok('C13 centralizar: data-al="c" + CSS nos 2 contextos', has(rte, "if(s==='center')return 'c';") && has(S, '.rte-ed [data-al="c"],.rte-view [data-al="c"]{text-align:center}'));
ok('C14 direita: data-al="r"', has(S, '.rte-ed [data-al="r"],.rte-view [data-al="r"]{text-align:right}'));
ok('C15 justificado: data-al="j"', has(S, '.rte-ed [data-al="j"],.rte-view [data-al="j"]{text-align:justify}'));
ok('C16 recuo: data-ind 1..6 + margem inflada no editável (outdent nativo enxerga)', has(rte, 'function rteEditableHtml(canon){') && has(rte, "margin-left:'+(Number(d)*40)+'px"));
ok('C17 desfazer: botão undo + Ctrl+Z nativo do CE (não interceptado)', has(rte, "_rteBtn('undo','Desfazer (Ctrl+Z)'") && has(wire, "if(k==='z'||k==='y'){ev.stopPropagation();return;"));
ok('C18 refazer: botão redo (Ctrl+Y nativo)', has(rte, "_rteBtn('redo','Refazer (Ctrl+Y)'"));
ok('C19 limpar formatação: removeFormat+unlink + strip dos spans de paleta/tamanho', has(rte, "document.execCommand('removeFormat');document.execCommand('unlink');") && has(rte, "ed.querySelectorAll('span[data-cl],span[data-hl],span[data-fs]')"));
ok('C20 atalhos NÃO vazam p/ o app (stopPropagation escopado ao editor)', count(wire, 'ev.stopPropagation()') >= 6 && has(wire, "var ed=ev.target&&ev.target.closest?ev.target.closest('.rte-ed'):null;\n    if(!ed)return;"));
ok('C21 colar do Word: text/html sanitizado ANTES de inserir (mso/class/id descartados) [RE-PINADO F3.5.5D: pipeline em _rtePasteApply]', has(wire, "htmlD=(ev.clipboardData&&ev.clipboardData.getData('text/html'))||'';") && has(wire, '_rtePasteApply(ed,htmlD,txt)') && has(pasteApply, 'var cl=rteSanitize(htmlD);if(cl){ins(cl);return;}'));
ok('C22 colar do Google Docs: listas aninhadas ACHATADAS determinísticas', has(sanit, 'function liInline(node,ctx,skipLists){') && has(sanit, 'if(skipLists)return;'));
ok('C23 colar HTML malicioso: perigosos somem COM o conteúdo', has(sanit, 'var DROP={SCRIPT:1,STYLE:1,IFRAME:1,OBJECT:1,EMBED:1,FORM:1,INPUT:1,BUTTON:1,SELECT:1,TEXTAREA:1,SVG:1,IMG:1,VIDEO:1,AUDIO:1,TEMPLATE:1,LINK:1,META:1,CANVAS:1,MAP:1,BASE:1,DIALOG:1};'));
ok('C24 script: SCRIPT no DROP (drop com corpo)', has(sanit, 'SCRIPT:1'));
ok('C25 iframe: IFRAME no DROP', has(sanit, 'IFRAME:1'));
ok('C26 onclick: NENHUM atributo do input é copiado — só data-* validados são emitidos', !has(sanit, 'getAttributeNames') && has(sanit, 'if(cl)attrs+=\' data-cl="\'+cl+\'"\';'));
ok('C27 link javascript:: href só http/https (regex anchored)', has(sanit, "/^https?:\\/\\//i.test(href)"));
ok('C28 parágrafos: blocos p canônicos; runs inline fundem em UM parágrafo', has(sanit, 'function blocks(node,ctx){') && has(sanit, "function flush(){if(run.trim())r+='<p'+pAttr+'>'+run+'</p>';run='';}"));
ok('C29 quebras de linha: <br> interno + <p><br></p> = linha vazia (projeção exata)', has(proj, ".replace(/\\n+$/,''))") && has(sanit, "if(tg==='BR'){if(run.trim())flush();else{run='';r+='<p'+pAttr+'><br></p>';}return;}"));
ok('C30 emojis: texto passa por esc() SEM normalização destrutiva', has(sanit, 'r+=esc(ch.nodeValue);'));
ok('C31 acentos: esc() escapa SÓ &<>"\'', has(S, "function esc(s){return (s==null?'':String(s)).replace(/[&<>\"']/g"));
ok('C32 texto longo: editor com max-height+scroll; Worker limita 120k', has(S, '.rte-ed{position:relative;min-height:64px;max-height:280px;overflow-y:auto;') && has(wrte, 'html.length > 120000'));
ok('C33 accordion: rteField dentro do .cb do content-card (toggle preservado)', has(brief, '<div class="cb"><div class="lbl">Tema</div>\'+rteField(\'form|\'+i+\'|tema\'') && has(brief, 'data-content="'));
ok('C34 rerender: input→rteSync grava NO MODELO (nunca re-render, nunca banco)', has(wire, "if(ed)rteSync(ed.getAttribute('data-rteed'),ed);") && !has(rte, 'db.collection'));
ok('C35 snapshot: rteSync sem render() (conteúdo sobrevive a re-render externo)', !/function rteSync\([\s\S]{0,900}render\(\)/.test(S));
ok('C36 avançar/voltar: rteField reconstrói do modelo (plain+rich com paridade)', has(rte, 'var initial=rteEditableHtml((rich&&rteParity(rich,plain))?rteSanitize(rich):plainToRich(plain));'));
ok('C37 revisão: legenda rica com PARIDADE + fallback esc de sempre', has(review, "(rteDisplayHtml(o.c.legendaRich,String(o.c.legenda))||esc(o.c.legenda))"));
ok('C38 salvar: coletores carregam rich SÓ quando existe', has(ce, 'if(m.temaRich)it.temaRich=m.temaRich;') && has(prod, 'if(it.temaRich)o.temaRich=it.temaRich;if(it.legendaRich)o.legendaRich=it.legendaRich;'));
ok('C39 reabrir: openContentEditor semeia modelo com plano+rico', has(ce, "window._ceModel=(conts.length?conts:[{}]).map(c=>({tema:c.tema||'',legenda:c.legenda||'',temaRich:c.temaRich||'',legendaRich:c.legendaRich||''}));"));
ok('C40 editar: 4 superfícies integradas (form/ce/fix/prod)', has(brief, "rteField('form|'") && has(ce, "rteField('ce|'") && has(fixo, "rteField('fix|'") && has(prod, "rteField('prod|'"));
ok('C41 copiar tema: cópia continua text/plain exata', has(copyd, "var _ps=(_node&&_node.querySelector)?_node.querySelector('.det-plain-src'):null;"));
ok('C42 copiar legenda: espelho oculto .det-plain-src com a projeção', has(det, "'<span class=\"det-plain-src\" hidden>'+esc(leg)+'</span>'"));
ok('C43 portal: Worker renderiza canônico VALIDADO no servidor (seção E)', wrte.length > 0);
ok('C44 aprovação individual: approveItem do Worker intocado', has(W, 'if (e.type === "approveItem") itemFields.cs = { stringValue: "aprovado" };'));
ok('C45 aprovar tudo: gate por fase preservado', has(W, 'if ((e.type === "approve" || e.type === "approveAll") && _pendingRev)'));
ok('C46 busca: nenhuma referência a temaRich fora do RTE/coletores (busca usa texto)', !/boardQuery[\s\S]{0,400}temaRich/.test(S));
ok('C47 notificações: nenhum produtor envia rich (payloads seguem texto)', !/notif[\s\S]{0,200}temaRich/i.test(S));
ok('C48 relatórios/desc: composedDesc segue nos campos texto', has(S, 'function composedDesc(){') && !/function composedDesc\(\)\{[\s\S]{0,800}Rich/.test(S));
ok('C49 tarefa antiga texto simples: sem rico → plainToRich no editor e esc() na exibição', has(rte, 'plainToRich(plain));') && has(rte, 'if(!rich)return null;'));
ok('C50 nenhuma execução insegura: display re-sanitiza + paridade obrigatória (defesa em profundidade)', has(rte, 'var clean=rteSanitize(rich);') && has(rte, "if(!clean||richToPlain(clean)!==String(plain==null?'':plain))return null;"));

console.log('— D) SEGURANÇA —');
ok('D1 sem CSP nova/afrouxada (renderer segue sem meta CSP — inalterado)', count(S, 'Content-Security-Policy') === 0);
ok('D2 execCommand APENAS como gesto (canônico = rteSanitize; documentado)', has(rte, 'O execCommand NUNCA é a fonte da verdade'));
ok('D3 zero dependência nova (deps exatas: electron-updater + firebase)', JSON.stringify(Object.keys(pkg.dependencies)) === JSON.stringify(['electron-updater', 'firebase']));
ok('D4 sem CDN/carregamento externo no RTE (sem <link>/@import/fetch/import())', !has(rte, '<link') && !has(rte, '@import') && !has(rte, 'fetch(') && !has(rte, 'import('));
ok('D5 colagem: fallback clipboard via IPC preservado [RE-PINADO F3.5.5D: em _rtePasteApply; clipboardReadHTML é read-only e SEMPRE passa pelo rteSanitize]', has(pasteApply, 'window.desktopAPI.clipboardReadText') && has(S, 'clipboardReadHTML') && has(S, '_rtePasteApply(ed,String(htmlD||\'\'),String(txt||\'\'))'));
ok('D6 links canônicos: rel="noopener noreferrer" target="_blank" FORÇADOS', has(sanit, '<a href="\'+esc(href)+\'" rel="noopener noreferrer" target="_blank">'));
ok('D7 estilos arbitrários NUNCA no canônico (só data-al/ind/cl/hl/fs)', !has(sanit, "attrs+=' style") && has(sanit, 'data-fs="'));
ok('D8 imagens externas automáticas: IMG no DROP (nem data-URL sobrevive)', has(sanit, 'IMG:1'));
ok('D9 conteúdo completo NUNCA em observabilidade (histórico limitado a 300 chars segue)', has(S, '.slice(0,300)') && !/cronDiag\([^)]*temaRich/.test(S));
ok('D10 menus do editor em position:fixed + fecha em scroll (sem tocar CSS legado)', has(rte, "panel.style.position='fixed';") && has(wire, "document.addEventListener('scroll',function(){if(_rteMenuOpen)_rteCloseMenus();},true);"));
ok('D11 seleção NUNCA vaza p/ outro editor (restore validado por container)', has(rte, 'if(_rteRange&&ed.contains(_rteRange.startContainer)){'));
ok('D12 rteSync roteado por fonte fechada (form|ce|fix|prod; nada dinâmico)', has(rte, "if(src==='form'&&state.form)") && has(rte, "else if(src==='prod'&&state._prod"));

console.log('— E) WORKER (portal) —');
ok('E1 gramática canônica validada token a token (fail-closed)', has(wrte, 'function rteWkValid(html) {') && has(wrte, 'return false;                                              // qualquer outra tag ⇒ rejeita'));
ok('E2 allowlist EXATA de blocos/atributos', has(wrte, 'block: /^<(p|h3|h4|li)( data-al="[crj]")?( data-ind="[1-6]")?>$/'));
ok('E3 spans só com data-cl/hl/fs válidos (span puro rejeitado)', has(wrte, 'span: /^<span( data-cl="[1-8]")?( data-hl="[1-6]")?( data-fs="(?:s|l|xl)")?>$/') && has(wrte, 't !== "<span>" && RTE_WK.span.test(t)'));
ok('E4 href http/https com rel/target FORÇADOS (regex fechada)', has(wrte, 'a: /^<a href="https?:\\/\\/[^"]+" rel="noopener noreferrer" target="_blank">$/'));
ok('E5 projeção IDÊNTICA à do Desktop (•/N./---/br-terminal/NBSP)', has(wrte, '(listT === "ul" ? "• " : (n + ". "))') && has(wrte, 'lines.push("---")') && has(wrte, '.replace(/\\u00A0/g, " ")'));
ok('E6 paridade OBRIGATÓRIA no servidor', has(wrte, 'if (rteWkPlain(rich) !== String(plain == null ? "" : plain)) return null;'));
ok('E7 render do tema: h3 inline single-p + campo com fallback escapado', has(wrender, "+ temaTitleHtml + '</h3></div>'") && has(wrender, '(temaRichHtml || tema)'));
ok('E8 render da legenda: rico validado OU escapeHtml de sempre', has(wrender, '(legRichHtml || escapeHtml(leg))'));
ok('E9 override do cliente DESLIGA o rico (edição em texto manda)', has(wrender, 'const temaRichHtml = temaOv ? null : rteWkDisplay(c.temaRich, temaPlainRaw);') && has(wrender, 'const legRichHtml = (typeof ov.legenda === "string") ? null : rteWkDisplay('));
ok('E10 data-plain preserva o texto EXATO p/ edição (getText prefere)', has(wrender, "' data-plain=\"' + rteWkAttrPlain(") && has(W, "var dp=el.getAttribute('data-plain');if(dp!=null)return dp;"));
ok('E11 /state intocado (texto puro; polling e assinaturas iguais)', !has(wstate, 'Rich') && has(wstate, 'legenda: (legRaw || "").toString()'));
ok('E12 gravações intocadas (writeClientGranular sem campos ricos)', !/writeClientGranular[\s\S]{0,3000}Rich/.test(W));
ok('E13 CSS .rtev com a MESMA paleta (8 cores + 6 destaques + 3 tamanhos)', count(W, '.rtev span[data-cl=') === 8 && count(W, '.rtev span[data-hl=') === 6 && count(W, '.rtev span[data-fs=') === 3);
ok('E14 identidade de versão viva V64.60-f355c-rich-render', has(W, '"V64.60-f355c-rich-render"'));
ok('E15 limite anti-DoS no validador (120k)', has(wrte, 'html.length > 120000) return false;'));
ok('E16 setTheme/setLegenda seguem texto puro (fallback ao vivo determinístico)', has(W, "function setTheme(i,v){var c=card(i);if(!c)return;var el=c.querySelector('[data-field=\"tema\"]');if(el)el.textContent=v;"));

console.log('— F) CONGELADOS / ISOLAMENTO —');
ok('F1 Agenda Premium 1.0.219 intacta (eventCard/openEventDetail presentes)', has(S, 'function eventCard(e){') && has(S, 'function openEventDetail(id,confirm){'));
ok('F2 card Kanban COMPACTO: kbv2/tcv4 seguem esc(c.tema) — sem render rico', /kbv2-theme|tcv4-theme-t/.test(S) && !/tcv4-theme[\s\S]{0,200}rteDisplay/.test(S) && !/kbv2[\s\S]{0,400}rteInlineDisplay/.test(S));
ok('F3 quantidade de VÍDEOS (F3.5.4V) intocada', has(S, 'var VIDEO_QTY_MAX=500;') && has(S, 'function normVideoQty(') && has(S, 'data-vqplus'));
ok('F4 observações internas por tema: privadas e escapadas (sem render rico)', has(det, "esc(_dn)") && has(det, 'det-acc-note'));
ok('F5 EXCLUIR digitado da exclusão preservado', has(S, "EXCLUIR"));
ok('F6 clipboard seguro detClipWrite preservado', has(S, 'async function detClipWrite'));
ok('F7 binds legados data-ctema/data-cleg permanecem inertes (sem elementos)', has(after, "bind('[data-ctema]'") && !has(brief, 'data-ctema="'));
ok('F8 dispatcher de quantidade ANTES do genérico [data-content] (sem conflito)', disp.length > 0);
ok('F9 Firebase compat e login intocados no RTE (nenhum firebase.* no núcleo)', !has(rte, 'firebase.'));
ok('F10 histórico do item-fix segue 300 chars em TEXTO', has(S, "oldValue:String(old).slice(0,300),newValue:String(val).slice(0,300)"));
ok('F11 worker-ops: rotas/notify/share intactos (âncoras vivas)', has(W, '"/notify-designer"') || has(W, "'/notify-designer'"));
ok('F12 modal de encolher usa data-modalbg-keep (não fecha no clique de fundo por engano)', has(qcore, 'data-modalbg-keep="1"'));

console.log('');
console.log('F3.5.5C script-quantity+rich-editor: ' + (n - fails) + '/' + n + (fails ? ' — FALHOU' : ' — VERDE'));
process.exit(fails ? 1 : 0);
