// I7.6 Composition C — OPERATIONAL COCKPIT. FULL standalone composition in ONE use_figma call.
// fileKey aG7NXRdpCaiRDMeBiT8EKu · skillNames resource:figma-use,resource:figma-generate-design
// Own sidebar. Board present but NOT dominant; STRONG right cockpit rail (~444) with 4 panels.
// Uses Card C component 5:2 (instance) + inline operational "A fazer" card. Placed at x=4000.
// PREPARED OFFLINE — not yet executed. After running: screenshot C frame, fix any clip/overlap surgically.
await figma.loadFontAsync({family:"Inter",style:"Regular"});
await figma.loadFontAsync({family:"Inter",style:"Medium"});
await figma.loadFontAsync({family:"Inter",style:"Semi Bold"});
await figma.loadFontAsync({family:"Inter",style:"Bold"});
const INK={r:0.086,g:0.137,b:0.231},INK2={r:0.259,g:0.314,b:0.420},INK3={r:0.482,g:0.529,b:0.616},W={r:1,g:1,b:1},LINE={r:0.863,g:0.890,b:0.925},S0={r:0.906,g:0.933,b:0.957},S1={r:0.933,g:0.953,b:0.972},S3={r:0.886,g:0.914,b:0.945},S4={r:0.929,g:0.949,b:0.965},TEAL={r:0.051,g:0.580,b:0.533},TEALS={r:0.078,g:0.722,b:0.651},TEALBG={r:0.914,g:0.969,b:0.961},TEALD={r:0.055,g:0.451,b:0.412},GREEN={r:0.133,g:0.773,b:0.369},PET={r:0.055,g:0.204,b:0.231},TODO={r:0.357,g:0.424,b:1.0},TODOBG={r:0.929,g:0.933,b:1.0},TODOTX={r:0.310,g:0.275,b:0.898},DOING={r:0.961,g:0.620,b:0.043},REVIEW={r:0.545,g:0.361,b:0.965},DONE={r:0.133,g:0.773,b:0.369},AMBBG={r:0.996,g:0.949,b:0.882},AMBTX={r:0.706,g:0.325,b:0.035};
const cardC=await figma.getNodeByIdAsync("5:2");
function icon(p,c,s){const n=figma.createNodeFromSvg(`<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`);n.resize(s,s);return n;}
const I={
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/>',
 user:'<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
 palette:'<circle cx="13.5" cy="6.5" r="1.2"/><circle cx="17.5" cy="10.5" r="1.2"/><circle cx="8.5" cy="7.5" r="1.2"/><circle cx="6.5" cy="12.5" r="1.2"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.9 0 1.6-.7 1.6-1.7 0-.4-.2-.8-.4-1.1-.3-.3-.4-.7-.4-1.1a1.6 1.6 0 0 1 1.6-1.6h2c3 0 5.5-2.5 5.5-5.6C22 6 17.5 2 12 2z"/>',
 share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 13.5 6.8 4"/><path d="m15.4 6.5-6.8 4"/>',
 folder:'<path d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.7-.9L9.6 3.9A2 2 0 0 0 7.9 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z"/>',
 plus:'<path d="M12 5v14M5 12h14"/>', chev:'<path d="m6 9 6 6 6-6"/>',
 cal:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',
 bar:'<path d="M3 3v18h18"/><rect x="7" y="11" width="3" height="7"/><rect x="12" y="7" width="3" height="11"/><rect x="17" y="14" width="3" height="4"/>',
 set:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.6 1.6 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.6 1.6 0 0 0-1.8-.3 1.6 1.6 0 0 0-1 1.5V21a2 2 0 0 1-4 0v-.1A1.6 1.6 0 0 0 9 19.4a1.6 1.6 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.6 1.6 0 0 0 .3-1.8 1.6 1.6 0 0 0-1.5-1H3a2 2 0 0 1 0-4h.1A1.6 1.6 0 0 0 4.6 9a1.6 1.6 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.6 1.6 0 0 0 1.8.3H9a1.6 1.6 0 0 0 1-1.5V3a2 2 0 0 1 4 0v.1a1.6 1.6 0 0 0 1 1.5 1.6 1.6 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.6 1.6 0 0 0-.3 1.8V9a1.6 1.6 0 0 0 1.5 1H21a2 2 0 0 1 0 4h-.1a1.6 1.6 0 0 0-1.5 1z"/>',
 search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',
 bell:'<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>',
 sliders:'<line x1="4" x2="4" y1="21" y2="14"/><line x1="4" x2="4" y1="10" y2="3"/><line x1="12" x2="12" y1="21" y2="12"/><line x1="12" x2="12" y1="8" y2="3"/><line x1="20" x2="20" y1="21" y2="16"/><line x1="20" x2="20" y1="12" y2="3"/><line x1="2" x2="6" y1="14" y2="14"/><line x1="10" x2="14" y1="8" y2="8"/><line x1="18" x2="22" y1="16" y2="16"/>',
 inbox:'<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/>'
};

/* FRAME C */
const C=figma.createFrame();C.name="C — Operational Cockpit";C.resize(1920,1080);C.x=4000;C.y=0;C.fills=[{type:'SOLID',color:S1}];C.clipsContent=true;

/* SIDEBAR (own) */
const sb=figma.createAutoLayout('VERTICAL',{name:"sidebar",itemSpacing:5});C.appendChild(sb);sb.x=0;sb.y=0;sb.resize(248,1080);sb.primaryAxisSizingMode="FIXED";sb.counterAxisSizingMode="FIXED";sb.paddingLeft=16;sb.paddingRight=16;sb.paddingTop=18;sb.paddingBottom=16;sb.fills=[{type:'SOLID',color:PET}];
const brand=figma.createAutoLayout('HORIZONTAL',{name:"brand",itemSpacing:11});brand.counterAxisAlignItems="CENTER";brand.fills=[];brand.paddingLeft=6;brand.paddingBottom=6;sb.appendChild(brand);
const logo=figma.createAutoLayout('HORIZONTAL',{name:"logo"});logo.primaryAxisAlignItems="CENTER";logo.counterAxisAlignItems="CENTER";logo.resize(34,34);logo.cornerRadius=9;logo.fills=[{type:'SOLID',color:TEALS}];brand.appendChild(logo);
const lg=figma.createText();lg.fontName={family:"Inter",style:"Bold"};lg.characters="7";lg.fontSize=17;lg.fills=[{type:'SOLID',color:{r:0.043,g:0.176,b:0.196}}];logo.appendChild(lg);
const wm=figma.createAutoLayout('VERTICAL',{name:"wm",itemSpacing:1});wm.fills=[];brand.appendChild(wm);
const w1=figma.createText();w1.fontName={family:"Inter",style:"Bold"};w1.characters="Agenda";w1.fontSize=15;w1.fills=[{type:'SOLID',color:W}];wm.appendChild(w1);
const w2=figma.createText();w2.fontName={family:"Inter",style:"Semi Bold"};w2.characters="ID SEVEN";w2.fontSize=8.5;w2.letterSpacing={unit:'PERCENT',value:16};w2.fills=[{type:'SOLID',color:W,opacity:0.5}];wm.appendChild(w2);
const nt=figma.createAutoLayout('HORIZONTAL',{name:"new-task",itemSpacing:8});nt.counterAxisAlignItems="CENTER";nt.primaryAxisAlignItems="CENTER";nt.paddingTop=11;nt.paddingBottom=11;nt.cornerRadius=10;nt.fills=[{type:'SOLID',color:TEAL}];sb.appendChild(nt);nt.layoutSizingHorizontal="FILL";nt.appendChild(icon(I.plus,"#FFFFFF",17));const ntt=figma.createText();ntt.fontName={family:"Inter",style:"Semi Bold"};ntt.characters="Nova tarefa";ntt.fontSize=13;ntt.fills=[{type:'SOLID',color:W}];nt.appendChild(ntt);
const lb=figma.createText();lb.fontName={family:"Inter",style:"Semi Bold"};lb.characters="PRINCIPAL";lb.fontSize=9.5;lb.letterSpacing={unit:'PERCENT',value:12};lb.fills=[{type:'SOLID',color:W,opacity:0.38}];sb.appendChild(lb);
function nav(paths,label,active){const it=figma.createAutoLayout('HORIZONTAL',{name:"nav/"+label,itemSpacing:11});it.counterAxisAlignItems="CENTER";it.paddingLeft=10;it.paddingRight=10;it.paddingTop=9;it.paddingBottom=9;it.cornerRadius=9;it.fills=active?[{type:'SOLID',color:W,opacity:0.09}]:[];it.appendChild(icon(paths,active?"#5EEAD4":"#7E9AA0",18));const t=figma.createText();t.fontName={family:"Inter",style:active?"Semi Bold":"Medium"};t.characters=label;t.fontSize=13;t.fills=[{type:'SOLID',color:W,opacity:active?1:0.74}];it.appendChild(t);sb.appendChild(it);it.layoutSizingHorizontal="FILL";}
nav(I.grid,"Meu quadro",true);nav(I.user,"Cliente",false);nav(I.palette,"Designers",false);nav(I.share,"Social Medias",false);nav(I.folder,"Setores",false);
const spc=figma.createFrame();spc.name="spacer";spc.fills=[];sb.appendChild(spc);spc.layoutSizingHorizontal="FILL";spc.layoutSizingVertical="FILL";
function nav2(paths,label){const it=figma.createAutoLayout('HORIZONTAL',{name:"nav/"+label,itemSpacing:11});it.counterAxisAlignItems="CENTER";it.paddingLeft=10;it.paddingRight=10;it.paddingTop=9;it.paddingBottom=9;it.cornerRadius=9;it.fills=[];it.appendChild(icon(paths,"#7E9AA0",18));const t=figma.createText();t.fontName={family:"Inter",style:"Medium"};t.characters=label;t.fontSize=13;t.fills=[{type:'SOLID',color:W,opacity:0.74}];it.appendChild(t);sb.appendChild(it);it.layoutSizingHorizontal="FILL";}
nav2(I.cal,"Calendário");nav2(I.bar,"Relatórios");nav2(I.set,"Configurações");
const dv=figma.createFrame();dv.name="div";dv.resize(216,1);dv.fills=[{type:'SOLID',color:W,opacity:0.10}];sb.appendChild(dv);dv.layoutSizingHorizontal="FILL";
const uf=figma.createAutoLayout('HORIZONTAL',{name:"user",itemSpacing:10});uf.counterAxisAlignItems="CENTER";uf.paddingTop=8;uf.paddingBottom=4;uf.fills=[];sb.appendChild(uf);uf.layoutSizingHorizontal="FILL";
const ua=figma.createAutoLayout('HORIZONTAL',{name:"uav"});ua.primaryAxisAlignItems="CENTER";ua.counterAxisAlignItems="CENTER";ua.resize(32,32);ua.cornerRadius=16;ua.fills=[{type:'SOLID',color:TEALS}];uf.appendChild(ua);const uai=figma.createText();uai.fontName={family:"Inter",style:"Bold"};uai.characters="CE";uai.fontSize=11;uai.fills=[{type:'SOLID',color:{r:0.043,g:0.176,b:0.196}}];ua.appendChild(uai);
const un=figma.createAutoLayout('VERTICAL',{name:"un",itemSpacing:1});un.fills=[];uf.appendChild(un);un.layoutSizingHorizontal="FILL";const un1=figma.createText();un1.fontName={family:"Inter",style:"Semi Bold"};un1.characters="Carlos Eduardo";un1.fontSize=12.5;un1.fills=[{type:'SOLID',color:W}];un.appendChild(un1);const un2=figma.createText();un2.fontName={family:"Inter",style:"Medium"};un2.characters="CEO · Id Seven";un2.fontSize=10;un2.fills=[{type:'SOLID',color:W,opacity:0.5}];un.appendChild(un2);uf.appendChild(icon(I.chev,"#7E9AA0",16));

/* HEADER */
const hd=figma.createFrame();hd.name="header";hd.resize(1672,60);hd.layoutMode="HORIZONTAL";hd.primaryAxisSizingMode="FIXED";hd.counterAxisSizingMode="FIXED";hd.primaryAxisAlignItems="SPACE_BETWEEN";hd.counterAxisAlignItems="CENTER";hd.paddingLeft=24;hd.paddingRight=24;hd.itemSpacing=20;hd.fills=[{type:'SOLID',color:{r:0.949,g:0.965,b:0.980}}];hd.strokes=[{type:'SOLID',color:LINE}];hd.strokeAlign="INSIDE";hd.strokeTopWeight=0;hd.strokeLeftWeight=0;hd.strokeRightWeight=0;hd.strokeBottomWeight=1;C.appendChild(hd);hd.x=248;hd.y=0;
const ctx=figma.createAutoLayout('VERTICAL',{name:"context",itemSpacing:2});ctx.fills=[];hd.appendChild(ctx);
const t1=figma.createText();t1.fontName={family:"Inter",style:"Bold"};t1.characters="Meu quadro";t1.fontSize=16.5;t1.letterSpacing={unit:'PERCENT',value:-1};t1.fills=[{type:'SOLID',color:INK}];ctx.appendChild(t1);
const t2=figma.createText();t2.fontName={family:"Inter",style:"Medium"};t2.characters="Cockpit operacional · 2 tarefas ativas";t2.fontSize=11.5;t2.fills=[{type:'SOLID',color:INK3}];ctx.appendChild(t2);
const seg=figma.createAutoLayout('HORIZONTAL',{name:"viewtabs",itemSpacing:2});seg.paddingTop=3;seg.paddingBottom=3;seg.paddingLeft=3;seg.paddingRight=3;seg.cornerRadius=10;seg.fills=[{type:'SOLID',color:S0}];seg.counterAxisAlignItems="CENTER";hd.appendChild(seg);
function tab(label,active){const p=figma.createAutoLayout('HORIZONTAL',{name:"tab/"+label});p.paddingTop=6;p.paddingBottom=6;p.paddingLeft=14;p.paddingRight=14;p.cornerRadius=8;p.primaryAxisAlignItems="CENTER";p.counterAxisAlignItems="CENTER";p.fills=active?[{type:'SOLID',color:W}]:[];if(active)p.effects=[{type:'DROP_SHADOW',color:{r:0.059,g:0.165,b:0.235,a:0.10},offset:{x:0,y:1},radius:2,spread:0,visible:true,blendMode:'NORMAL'}];const t=figma.createText();t.fontName={family:"Inter",style:active?"Semi Bold":"Medium"};t.characters=label;t.fontSize=12.5;t.fills=[{type:'SOLID',color:active?INK:INK3}];p.appendChild(t);seg.appendChild(p);}
tab("Quadro",true);tab("Timeline",false);tab("Lista",false);
const rg=figma.createAutoLayout('HORIZONTAL',{name:"actions",itemSpacing:12});rg.fills=[];rg.counterAxisAlignItems="CENTER";hd.appendChild(rg);
const sf=figma.createAutoLayout('HORIZONTAL',{name:"search",itemSpacing:9});sf.paddingLeft=12;sf.paddingRight=12;sf.cornerRadius=9;sf.counterAxisAlignItems="CENTER";sf.fills=[{type:'SOLID',color:W}];sf.strokes=[{type:'SOLID',color:LINE}];sf.resize(210,36);sf.primaryAxisSizingMode="FIXED";sf.counterAxisSizingMode="FIXED";rg.appendChild(sf);sf.appendChild(icon(I.search,"#7B879D",16));const spf=figma.createText();spf.fontName={family:"Inter",style:"Regular"};spf.characters="Buscar…";spf.fontSize=12.5;spf.fills=[{type:'SOLID',color:INK3}];sf.appendChild(spf);
const bell=figma.createAutoLayout('HORIZONTAL',{name:"notif"});bell.resize(36,36);bell.cornerRadius=9;bell.primaryAxisAlignItems="CENTER";bell.counterAxisAlignItems="CENTER";bell.fills=[{type:'SOLID',color:W}];bell.strokes=[{type:'SOLID',color:LINE}];rg.appendChild(bell);bell.appendChild(icon(I.bell,"#42506B",18));
const av0=figma.createAutoLayout('HORIZONTAL',{name:"avatar"});av0.resize(34,34);av0.cornerRadius=17;av0.primaryAxisAlignItems="CENTER";av0.counterAxisAlignItems="CENTER";av0.fills=[{type:'SOLID',color:TEAL}];rg.appendChild(av0);const ai0=figma.createText();ai0.fontName={family:"Inter",style:"Bold"};ai0.characters="CE";ai0.fontSize=11;ai0.fills=[{type:'SOLID',color:W}];av0.appendChild(ai0);

/* VIEW CONTROLS */
const cb=figma.createFrame();cb.name="view-controls";cb.resize(1672,48);cb.layoutMode="HORIZONTAL";cb.primaryAxisSizingMode="FIXED";cb.counterAxisSizingMode="FIXED";cb.primaryAxisAlignItems="SPACE_BETWEEN";cb.counterAxisAlignItems="CENTER";cb.paddingLeft=24;cb.paddingRight=24;cb.fills=[];C.appendChild(cb);cb.x=248;cb.y=60;
const cbl=figma.createAutoLayout('HORIZONTAL',{name:"cbl",itemSpacing:10});cbl.fills=[];cbl.counterAxisAlignItems="CENTER";cb.appendChild(cbl);
function chip(build){const c=figma.createAutoLayout('HORIZONTAL',{name:"chip",itemSpacing:7});c.paddingTop=6;c.paddingBottom=6;c.paddingLeft=9;c.paddingRight=10;c.cornerRadius=9;c.counterAxisAlignItems="CENTER";c.fills=[{type:'SOLID',color:W}];c.strokes=[{type:'SOLID',color:LINE}];cbl.appendChild(c);build(c);return c;}
chip(c=>{const a=figma.createAutoLayout('HORIZONTAL');a.resize(20,20);a.cornerRadius=10;a.primaryAxisAlignItems="CENTER";a.counterAxisAlignItems="CENTER";a.fills=[{type:'SOLID',color:TEAL}];c.appendChild(a);const at=figma.createText();at.fontName={family:"Inter",style:"Bold"};at.characters="CE";at.fontSize=8.5;at.fills=[{type:'SOLID',color:W}];a.appendChild(at);const tx=figma.createText();tx.fontName={family:"Inter",style:"Medium"};tx.characters="Carlos Eduardo";tx.fontSize=12;tx.fills=[{type:'SOLID',color:INK2}];c.appendChild(tx);c.appendChild(icon(I.chev,"#7B879D",14));});
chip(c=>{const tx=figma.createText();tx.fontName={family:"Inter",style:"Medium"};tx.characters="Equipe: Todos";tx.fontSize=12;tx.fills=[{type:'SOLID',color:INK2}];c.appendChild(tx);c.appendChild(icon(I.chev,"#7B879D",14));});
chip(c=>{c.appendChild(icon(I.sliders,"#42506B",15));const tx=figma.createText();tx.fontName={family:"Inter",style:"Medium"};tx.characters="Filtros";tx.fontSize=12;tx.fills=[{type:'SOLID',color:INK2}];c.appendChild(tx);});
const cbr=figma.createText();cbr.fontName={family:"Inter",style:"Medium"};cbr.characters="2 tarefas nesta visão";cbr.fontSize=12;cbr.fills=[{type:'SOLID',color:INK3}];cb.appendChild(cbr);

/* BOARD (narrower, Card C) */
function makeTodoCardC(){const c=figma.createAutoLayout('VERTICAL',{name:"card/todo",itemSpacing:8});c.paddingTop=12;c.paddingBottom=12;c.paddingLeft=15;c.paddingRight=13;c.cornerRadius=12;c.fills=[{type:'SOLID',color:W}];c.strokes=[{type:'SOLID',color:LINE}];c.effects=[{type:'DROP_SHADOW',color:{r:0.059,g:0.165,b:0.235,a:0.06},offset:{x:0,y:1},radius:2,spread:0,visible:true,blendMode:'NORMAL'}];
 const eye=figma.createText();eye.fontName={family:"Inter",style:"Semi Bold"};eye.characters="SUNSET WEAR";eye.fontSize=9;eye.letterSpacing={unit:'PERCENT',value:8};eye.fills=[{type:'SOLID',color:INK3}];c.appendChild(eye);
 const ti=figma.createText();ti.fontName={family:"Inter",style:"Bold"};ti.characters="Reels de lançamento";ti.fontSize=14;ti.lineHeight={unit:'PERCENT',value:126};ti.fills=[{type:'SOLID',color:INK}];c.appendChild(ti);ti.layoutSizingHorizontal="FILL";
 const st=figma.createAutoLayout('HORIZONTAL',{name:"stage",itemSpacing:6});st.fills=[];st.counterAxisAlignItems="CENTER";c.appendChild(st);const sdc=figma.createEllipse();sdc.resize(7,7);sdc.fills=[{type:'SOLID',color:TODO}];st.appendChild(sdc);const stg=figma.createText();stg.fontName={family:"Inter",style:"Medium"};stg.characters="A fazer";stg.fontSize=11;stg.fills=[{type:'SOLID',color:INK2}];st.appendChild(stg);
 const foot=figma.createAutoLayout('HORIZONTAL',{name:"foot",itemSpacing:8});foot.fills=[];foot.counterAxisAlignItems="CENTER";c.appendChild(foot);foot.layoutSizingHorizontal="FILL";foot.primaryAxisAlignItems="SPACE_BETWEEN";
 const av=figma.createAutoLayout('HORIZONTAL');av.resize(22,22);av.cornerRadius=11;av.primaryAxisAlignItems="CENTER";av.counterAxisAlignItems="CENTER";av.fills=[{type:'SOLID',color:TEAL}];foot.appendChild(av);const ai=figma.createText();ai.fontName={family:"Inter",style:"Bold"};ai.characters="CE";ai.fontSize=9;ai.fills=[{type:'SOLID',color:W}];av.appendChild(ai);
 const due=figma.createText();due.fontName={family:"Inter",style:"Medium"};due.characters="vence 26/08";due.fontSize=11;due.fills=[{type:'SOLID',color:INK3}];foot.appendChild(due);
 const bar=figma.createRectangle();bar.resize(3,50);bar.fills=[{type:'SOLID',color:TODO}];bar.topLeftRadius=12;bar.bottomLeftRadius=12;c.appendChild(bar);bar.layoutPositioning="ABSOLUTE";bar.constraints={horizontal:"MIN",vertical:"STRETCH"};bar.x=0;bar.y=0;return c;}
function makeEmpty(){const e=figma.createAutoLayout('VERTICAL',{name:"empty",itemSpacing:7});e.primaryAxisAlignItems="CENTER";e.counterAxisAlignItems="CENTER";e.paddingTop=24;e.paddingBottom=24;e.paddingLeft=10;e.paddingRight=10;e.cornerRadius=11;e.fills=[];e.strokes=[{type:'SOLID',color:{r:0.820,g:0.855,b:0.898}}];e.dashPattern=[5,5];e.appendChild(icon(I.inbox,"#9AA6B8",20));const q1=figma.createText();q1.fontName={family:"Inter",style:"Semi Bold"};q1.characters="Sem tarefas";q1.fontSize=11;q1.fills=[{type:'SOLID',color:INK3}];e.appendChild(q1);return e;}
const well=figma.createFrame();well.name="board";well.layoutMode="HORIZONTAL";well.itemSpacing=11;well.paddingTop=14;well.paddingBottom=14;well.paddingLeft=14;well.paddingRight=14;well.cornerRadius=16;well.fills=[{type:'SOLID',color:S3}];C.appendChild(well);well.x=268;well.y=128;well.resize(1168,470);well.primaryAxisSizingMode="FIXED";well.counterAxisSizingMode="AUTO";well.counterAxisAlignItems="STRETCH";
const stages=[{n:"A Fazer",c:TODO,k:1,t:"todo"},{n:"Em andamento",c:DOING,k:1,t:"doing"},{n:"Revisão",c:REVIEW,k:0,t:"empty"},{n:"Finalizado",c:DONE,k:0,t:"empty"}];
for(const s of stages){
 const col=figma.createAutoLayout('VERTICAL',{name:"col/"+s.n,itemSpacing:9});col.paddingTop=10;col.paddingBottom=12;col.paddingLeft=9;col.paddingRight=9;col.cornerRadius=14;col.fills=[{type:'SOLID',color:S4}];well.appendChild(col);col.layoutSizingHorizontal="FILL";col.minHeight=438;
 const h=figma.createAutoLayout('HORIZONTAL',{name:"colhead"});h.fills=[];h.counterAxisAlignItems="CENTER";h.primaryAxisAlignItems="SPACE_BETWEEN";h.paddingLeft=4;h.paddingRight=2;h.paddingTop=2;h.paddingBottom=2;col.appendChild(h);h.layoutSizingHorizontal="FILL";
 const hl=figma.createAutoLayout('HORIZONTAL',{name:"hl",itemSpacing:7});hl.fills=[];hl.counterAxisAlignItems="CENTER";h.appendChild(hl);const dot=figma.createEllipse();dot.resize(8,8);dot.fills=[{type:'SOLID',color:s.c}];hl.appendChild(dot);const ht=figma.createText();ht.fontName={family:"Inter",style:"Semi Bold"};ht.characters=s.n;ht.fontSize=12;ht.fills=[{type:'SOLID',color:INK}];hl.appendChild(ht);
 const cpp=figma.createAutoLayout('HORIZONTAL');cpp.paddingLeft=6;cpp.paddingRight=6;cpp.paddingTop=2;cpp.paddingBottom=2;cpp.cornerRadius=8;cpp.fills=[{type:'SOLID',color:S0}];cpp.counterAxisAlignItems="CENTER";h.appendChild(cpp);const cptx=figma.createText();cptx.fontName={family:"Inter",style:"Bold"};cptx.characters=String(s.k);cptx.fontSize=10;cptx.fills=[{type:'SOLID',color:INK3}];cpp.appendChild(cptx);
 if(s.t==="doing"){const inst=cardC.createInstance();col.appendChild(inst);inst.layoutSizingHorizontal="FILL";}
 else if(s.t==="todo"){const cd=makeTodoCardC();col.appendChild(cd);cd.layoutSizingHorizontal="FILL";}
 else{const es=makeEmpty();col.appendChild(es);es.layoutSizingHorizontal="FILL";}
}

/* COCKPIT RAIL (strong, 4 panels) */
const rail=figma.createAutoLayout('VERTICAL',{name:"cockpit-rail",itemSpacing:12});rail.fills=[];C.appendChild(rail);rail.x=1456;rail.y=128;rail.resize(444,10);rail.primaryAxisSizingMode="AUTO";rail.counterAxisSizingMode="FIXED";
function panel(title){const p=figma.createAutoLayout('VERTICAL',{name:"panel/"+title,itemSpacing:12});p.paddingTop=16;p.paddingBottom=16;p.paddingLeft=16;p.paddingRight=16;p.cornerRadius=14;p.fills=[{type:'SOLID',color:W}];p.strokes=[{type:'SOLID',color:LINE}];rail.appendChild(p);p.layoutSizingHorizontal="FILL";const t=figma.createText();t.fontName={family:"Inter",style:"Semi Bold"};t.characters=title;t.fontSize=12.5;t.fills=[{type:'SOLID',color:INK}];p.appendChild(t);return p;}
// P1 Resumo operacional (4 tiles)
const p1=panel("Resumo operacional");const grid=figma.createAutoLayout('VERTICAL',{name:"grid",itemSpacing:9});grid.fills=[];p1.appendChild(grid);grid.layoutSizingHorizontal="FILL";
function tileRow(a,b){const r=figma.createAutoLayout('HORIZONTAL',{name:"r",itemSpacing:9});r.fills=[];grid.appendChild(r);r.layoutSizingHorizontal="FILL";[a,b].forEach(o=>{const t=figma.createAutoLayout('VERTICAL',{name:"tile",itemSpacing:3});t.paddingTop=12;t.paddingBottom=12;t.paddingLeft=13;t.paddingRight=13;t.cornerRadius=10;t.fills=[{type:'SOLID',color:S0}];r.appendChild(t);t.layoutSizingHorizontal="FILL";const v=figma.createText();v.fontName={family:"Inter",style:"Bold"};v.characters=o.v;v.fontSize=19;v.fills=[{type:'SOLID',color:o.c}];t.appendChild(v);const l=figma.createText();l.fontName={family:"Inter",style:"Medium"};l.characters=o.l;l.fontSize=10.5;l.fills=[{type:'SOLID',color:INK3}];t.appendChild(l);});}
tileRow({v:"2",l:"Total",c:INK},{v:"1",l:"Em andamento",c:DOING});tileRow({v:"1",l:"A fazer",c:TODO},{v:"0",l:"Concluídas",c:DONE});
// P2 SLA da visão (prominent)
const p2=panel("SLA da visão");
const bigrow=figma.createAutoLayout('HORIZONTAL',{name:"bigrow"});bigrow.fills=[];bigrow.primaryAxisAlignItems="SPACE_BETWEEN";bigrow.counterAxisAlignItems="CENTER";p2.appendChild(bigrow);bigrow.layoutSizingHorizontal="FILL";
const bl=figma.createAutoLayout('VERTICAL',{name:"bl",itemSpacing:2});bl.fills=[];bigrow.appendChild(bl);const bv=figma.createText();bv.fontName={family:"Inter",style:"Bold"};bv.characters="Hoje · 22:00";bv.fontSize=20;bv.fills=[{type:'SOLID',color:INK}];bl.appendChild(bv);const bl2=figma.createText();bl2.fontName={family:"Inter",style:"Medium"};bl2.characters="Próximo vencimento";bl2.fontSize=11;bl2.fills=[{type:'SOLID',color:INK3}];bl.appendChild(bl2);
const bg=figma.createAutoLayout('HORIZONTAL',{name:"badge",itemSpacing:6});bg.paddingTop=6;bg.paddingBottom=6;bg.paddingLeft=10;bg.paddingRight=11;bg.cornerRadius=8;bg.fills=[{type:'SOLID',color:TEALBG}];bg.counterAxisAlignItems="CENTER";bigrow.appendChild(bg);const bgd=figma.createEllipse();bgd.resize(7,7);bgd.fills=[{type:'SOLID',color:GREEN}];bg.appendChild(bgd);const bgt=figma.createText();bgt.fontName={family:"Inter",style:"Semi Bold"};bgt.characters="No prazo";bgt.fontSize=11.5;bgt.fills=[{type:'SOLID',color:TEALD}];bg.appendChild(bgt);
const track=figma.createFrame();track.name="sla-track";track.resize(400,6);track.cornerRadius=3;track.fills=[{type:'SOLID',color:S3}];track.clipsContent=true;p2.appendChild(track);track.layoutSizingHorizontal="FILL";const fillr=figma.createRectangle();fillr.resize(300,6);fillr.cornerRadius=3;fillr.fills=[{type:'SOLID',color:GREEN}];track.appendChild(fillr);fillr.x=0;fillr.y=0;
const slcap=figma.createText();slcap.fontName={family:"Inter",style:"Medium"};slcap.characters="1 de 2 tarefas com prazo · 0 em risco";slcap.fontSize=11;slcap.fills=[{type:'SOLID',color:INK3}];p2.appendChild(slcap);slcap.layoutSizingHorizontal="FILL";
// P3 Equipe & carga
const p3=panel("Equipe & carga");
function member(txt,color,name,role,load,pct){const m=figma.createAutoLayout('VERTICAL',{name:"m",itemSpacing:7});m.fills=[];p3.appendChild(m);m.layoutSizingHorizontal="FILL";const top=figma.createAutoLayout('HORIZONTAL',{name:"top",itemSpacing:10});top.fills=[];top.counterAxisAlignItems="CENTER";top.primaryAxisAlignItems="SPACE_BETWEEN";m.appendChild(top);top.layoutSizingHorizontal="FILL";const left=figma.createAutoLayout('HORIZONTAL',{name:"l",itemSpacing:10});left.fills=[];left.counterAxisAlignItems="CENTER";top.appendChild(left);const a=figma.createAutoLayout('HORIZONTAL');a.resize(30,30);a.cornerRadius=15;a.primaryAxisAlignItems="CENTER";a.counterAxisAlignItems="CENTER";a.fills=[{type:'SOLID',color}];left.appendChild(a);const ai=figma.createText();ai.fontName={family:"Inter",style:"Bold"};ai.characters=txt;ai.fontSize=10;ai.fills=[{type:'SOLID',color:W}];a.appendChild(ai);const nn=figma.createAutoLayout('VERTICAL',{name:"nn",itemSpacing:1});nn.fills=[];left.appendChild(nn);const n1=figma.createText();n1.fontName={family:"Inter",style:"Semi Bold"};n1.characters=name;n1.fontSize=12;n1.fills=[{type:'SOLID',color:INK}];nn.appendChild(n1);const n2=figma.createText();n2.fontName={family:"Inter",style:"Medium"};n2.characters=role;n2.fontSize=10;n2.fills=[{type:'SOLID',color:INK3}];nn.appendChild(n2);const cc=figma.createText();cc.fontName={family:"Inter",style:"Bold"};cc.characters=load;cc.fontSize=11;cc.fills=[{type:'SOLID',color:INK3}];top.appendChild(cc);const tr=figma.createFrame();tr.name="load";tr.resize(400,5);tr.cornerRadius=3;tr.fills=[{type:'SOLID',color:S3}];tr.clipsContent=true;m.appendChild(tr);tr.layoutSizingHorizontal="FILL";const fl=figma.createRectangle();fl.resize(pct,5);fl.cornerRadius=3;fl.fills=[{type:'SOLID',color}];tr.appendChild(fl);fl.x=0;fl.y=0;}
member("CE",TEAL,"Carlos Eduardo","CEO · Operações","2 tarefas",180);
member("MK",REVIEW,"Marina Klein","Designer","0 tarefas",0);
// P4 Próximas entregas
const p4=panel("Próximas entregas");
function due(color,title,when){const r=figma.createAutoLayout('HORIZONTAL',{name:"due",itemSpacing:10});r.fills=[];r.counterAxisAlignItems="CENTER";r.primaryAxisAlignItems="SPACE_BETWEEN";p4.appendChild(r);r.layoutSizingHorizontal="FILL";const l=figma.createAutoLayout('HORIZONTAL',{name:"dl",itemSpacing:9});l.fills=[];l.counterAxisAlignItems="CENTER";r.appendChild(l);const d=figma.createEllipse();d.resize(8,8);d.fills=[{type:'SOLID',color}];l.appendChild(d);const tt=figma.createText();tt.fontName={family:"Inter",style:"Medium"};tt.characters=title;tt.fontSize=12;tt.fills=[{type:'SOLID',color:INK2}];l.appendChild(tt);const wt=figma.createText();wt.fontName={family:"Inter",style:"Semi Bold"};wt.characters=when;wt.fontSize=11;wt.fills=[{type:'SOLID',color:INK3}];r.appendChild(wt);}
due(DOING,"Cronograma Sunset Wear","hoje 22:00");due(TODO,"Reels de lançamento","26/08");
return { C:C.id, sidebar:sb.id, board:well.id, rail:rail.id, ok:true };
