// I7.6 Composition A — KANBAN-CENTRIC. FULL standalone composition in ONE use_figma call.
// fileKey aG7NXRdpCaiRDMeBiT8EKu · skillNames resource:figma-use,resource:figma-generate-design
// Own sidebar (separate frame). Board DOMINANT, NO right rail (context folded into a compact KPI strip).
// Uses Card A component 3:2 (instance) + one inline minimal "A fazer" card. Placed at x=2000 (beside B).
// PREPARED OFFLINE — not yet executed/visually verified. After running: screenshot A frame, fix any clip/overlap surgically.
await figma.loadFontAsync({family:"Inter",style:"Regular"});
await figma.loadFontAsync({family:"Inter",style:"Medium"});
await figma.loadFontAsync({family:"Inter",style:"Semi Bold"});
await figma.loadFontAsync({family:"Inter",style:"Bold"});
const INK={r:0.086,g:0.137,b:0.231},INK2={r:0.259,g:0.314,b:0.420},INK3={r:0.482,g:0.529,b:0.616},W={r:1,g:1,b:1},LINE={r:0.863,g:0.890,b:0.925},S0={r:0.906,g:0.933,b:0.957},S1={r:0.933,g:0.953,b:0.972},S3={r:0.886,g:0.914,b:0.945},S4={r:0.929,g:0.949,b:0.965},TEAL={r:0.051,g:0.580,b:0.533},TEALS={r:0.078,g:0.722,b:0.651},TEALBG={r:0.914,g:0.969,b:0.961},TEALD={r:0.055,g:0.451,b:0.412},GREEN={r:0.133,g:0.773,b:0.369},PET={r:0.055,g:0.204,b:0.231},TODO={r:0.357,g:0.424,b:1.0},TODOBG={r:0.929,g:0.933,b:1.0},TODOTX={r:0.310,g:0.275,b:0.898},DOING={r:0.961,g:0.620,b:0.043},REVIEW={r:0.545,g:0.361,b:0.965},DONE={r:0.133,g:0.773,b:0.369};
const cardA=await figma.getNodeByIdAsync("3:2");
function icon(p,c,s){const n=figma.createNodeFromSvg(`<svg width="${s}" height="${s}" viewBox="0 0 24 24" fill="none" stroke="${c}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${p}</svg>`);n.resize(s,s);return n;}
const I={
 grid:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/>',
 user:'<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
 palette:'<circle cx="13.5" cy="6.5" r="1.2"/><circle cx="17.5" cy="10.5" r="1.2"/><circle cx="8.5" cy="7.5" r="1.2"/><circle cx="6.5" cy="12.5" r="1.2"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.9 0 1.6-.7 1.6-1.7 0-.4-.2-.8-.4-1.1-.3-.3-.4-.7-.4-1.1a1.6 1.6 0 0 1 1.6-1.6h2c3 0 5.5-2.5 5.5-5.6C22 6 17.5 2 12 2z"/>',
 share:'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 13.5 6.8 4"/><path d="m15.4 6.5-6.8 4"/>',
 folder:'<path d="M4 20h16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.7-.9L9.6 3.9A2 2 0 0 0 7.9 3H4a2 2 0 0 0-2 2v13c0 1.1.9 2 2 2Z"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 cal:'<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>',
 bar:'<path d="M3 3v18h18"/><rect x="7" y="11" width="3" height="7"/><rect x="12" y="7" width="3" height="11"/><rect x="17" y="14" width="3" height="4"/>',
 set:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.6 1.6 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.6 1.6 0 0 0-1.8-.3 1.6 1.6 0 0 0-1 1.5V21a2 2 0 0 1-4 0v-.1A1.6 1.6 0 0 0 9 19.4a1.6 1.6 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1-.1a1.6 1.6 0 0 0 .3-1.8 1.6 1.6 0 0 0-1.5-1H3a2 2 0 0 1 0-4h.1A1.6 1.6 0 0 0 4.6 9a1.6 1.6 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.6 1.6 0 0 0 1.8.3H9a1.6 1.6 0 0 0 1-1.5V3a2 2 0 0 1 4 0v.1a1.6 1.6 0 0 0 1 1.5 1.6 1.6 0 0 0 1.8-.3l.1-.1a2 2 0 1 1 2.8 2.8l-.1.1a1.6 1.6 0 0 0-.3 1.8V9a1.6 1.6 0 0 0 1.5 1H21a2 2 0 0 1 0 4h-.1a1.6 1.6 0 0 0-1.5 1z"/>',
 chev:'<path d="m6 9 6 6 6-6"/>',
 search:'<circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/>',
 bell:'<path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"/><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"/>',
 sliders:'<line x1="4" x2="4" y1="21" y2="14"/><line x1="4" x2="4" y1="10" y2="3"/><line x1="12" x2="12" y1="21" y2="12"/><line x1="12" x2="12" y1="8" y2="3"/><line x1="20" x2="20" y1="21" y2="16"/><line x1="20" x2="20" y1="12" y2="3"/><line x1="2" x2="6" y1="14" y2="14"/><line x1="10" x2="14" y1="8" y2="8"/><line x1="18" x2="22" y1="16" y2="16"/>',
 inbox:'<path d="M22 12h-6l-2 3h-4l-2-3H2"/><path d="M5.45 5.11 2 12v6a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-6l-3.45-6.89A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z"/>'
};

/* FRAME A */
const A=figma.createFrame();A.name="A — Kanban-centric";A.resize(1920,1080);A.x=2000;A.y=0;A.fills=[{type:'SOLID',color:S1}];A.clipsContent=true;

/* SIDEBAR (own) */
const sb=figma.createAutoLayout('VERTICAL',{name:"sidebar",itemSpacing:5});A.appendChild(sb);sb.x=0;sb.y=0;sb.resize(248,1080);sb.primaryAxisSizingMode="FIXED";sb.counterAxisSizingMode="FIXED";sb.paddingLeft=16;sb.paddingRight=16;sb.paddingTop=18;sb.paddingBottom=16;sb.fills=[{type:'SOLID',color:PET}];
const brand=figma.createAutoLayout('HORIZONTAL',{name:"brand",itemSpacing:11});brand.counterAxisAlignItems="CENTER";brand.fills=[];brand.paddingLeft=6;brand.paddingBottom=6;sb.appendChild(brand);
const logo=figma.createAutoLayout('HORIZONTAL',{name:"logo"});logo.primaryAxisAlignItems="CENTER";logo.counterAxisAlignItems="CENTER";logo.resize(34,34);logo.cornerRadius=9;logo.fills=[{type:'SOLID',color:TEALS}];brand.appendChild(logo);
const lg=figma.createText();lg.fontName={family:"Inter",style:"Bold"};lg.characters="7";lg.fontSize=17;lg.fills=[{type:'SOLID',color:{r:0.043,g:0.176,b:0.196}}];logo.appendChild(lg);
const wm=figma.createAutoLayout('VERTICAL',{name:"wm",itemSpacing:1});wm.fills=[];brand.appendChild(wm);
const w1=figma.createText();w1.fontName={family:"Inter",style:"Bold"};w1.characters="Agenda";w1.fontSize=15;w1.fills=[{type:'SOLID',color:W}];wm.appendChild(w1);
const w2=figma.createText();w2.fontName={family:"Inter",style:"Semi Bold"};w2.characters="ID SEVEN";w2.fontSize=8.5;w2.letterSpacing={unit:'PERCENT',value:16};w2.fills=[{type:'SOLID',color:W,opacity:0.5}];wm.appendChild(w2);
const nt=figma.createAutoLayout('HORIZONTAL',{name:"new-task",itemSpacing:8});nt.counterAxisAlignItems="CENTER";nt.primaryAxisAlignItems="CENTER";nt.paddingTop=11;nt.paddingBottom=11;nt.cornerRadius=10;nt.fills=[{type:'SOLID',color:TEAL}];sb.appendChild(nt);nt.layoutSizingHorizontal="FILL";
nt.appendChild(icon(I.plus,"#FFFFFF",17));const ntt=figma.createText();ntt.fontName={family:"Inter",style:"Semi Bold"};ntt.characters="Nova tarefa";ntt.fontSize=13;ntt.fills=[{type:'SOLID',color:W}];nt.appendChild(ntt);
const lb=figma.createText();lb.fontName={family:"Inter",style:"Semi Bold"};lb.characters="PRINCIPAL";lb.fontSize=9.5;lb.letterSpacing={unit:'PERCENT',value:12};lb.fills=[{type:'SOLID',color:W,opacity:0.38}];sb.appendChild(lb);
function nav(paths,label,active){const it=figma.createAutoLayout('HORIZONTAL',{name:"nav/"+label,itemSpacing:11});it.counterAxisAlignItems="CENTER";it.paddingLeft=10;it.paddingRight=10;it.paddingTop=9;it.paddingBottom=9;it.cornerRadius=9;it.fills=active?[{type:'SOLID',color:W,opacity:0.09}]:[];it.appendChild(icon(paths,active?"#5EEAD4":"#7E9AA0",18));const t=figma.createText();t.fontName={family:"Inter",style:active?"Semi Bold":"Medium"};t.characters=label;t.fontSize=13;t.fills=[{type:'SOLID',color:W,opacity:active?1:0.74}];it.appendChild(t);sb.appendChild(it);it.layoutSizingHorizontal="FILL";}
nav(I.grid,"Meu quadro",true);nav(I.user,"Cliente",false);nav(I.palette,"Designers",false);nav(I.share,"Social Medias",false);nav(I.folder,"Setores",false);
const sp=figma.createFrame();sp.name="spacer";sp.fills=[];sb.appendChild(sp);sp.layoutSizingHorizontal="FILL";sp.layoutSizingVertical="FILL";
function nav2(paths,label){const it=figma.createAutoLayout('HORIZONTAL',{name:"nav/"+label,itemSpacing:11});it.counterAxisAlignItems="CENTER";it.paddingLeft=10;it.paddingRight=10;it.paddingTop=9;it.paddingBottom=9;it.cornerRadius=9;it.fills=[];it.appendChild(icon(paths,"#7E9AA0",18));const t=figma.createText();t.fontName={family:"Inter",style:"Medium"};t.characters=label;t.fontSize=13;t.fills=[{type:'SOLID',color:W,opacity:0.74}];it.appendChild(t);sb.appendChild(it);it.layoutSizingHorizontal="FILL";}
nav2(I.cal,"Calendário");nav2(I.bar,"Relatórios");nav2(I.set,"Configurações");
const dv=figma.createFrame();dv.name="div";dv.resize(216,1);dv.fills=[{type:'SOLID',color:W,opacity:0.10}];sb.appendChild(dv);dv.layoutSizingHorizontal="FILL";
const uf=figma.createAutoLayout('HORIZONTAL',{name:"user",itemSpacing:10});uf.counterAxisAlignItems="CENTER";uf.paddingTop=8;uf.paddingBottom=4;uf.fills=[];sb.appendChild(uf);uf.layoutSizingHorizontal="FILL";
const ua=figma.createAutoLayout('HORIZONTAL',{name:"uav"});ua.primaryAxisAlignItems="CENTER";ua.counterAxisAlignItems="CENTER";ua.resize(32,32);ua.cornerRadius=16;ua.fills=[{type:'SOLID',color:TEALS}];uf.appendChild(ua);
const uai=figma.createText();uai.fontName={family:"Inter",style:"Bold"};uai.characters="CE";uai.fontSize=11;uai.fills=[{type:'SOLID',color:{r:0.043,g:0.176,b:0.196}}];ua.appendChild(uai);
const un=figma.createAutoLayout('VERTICAL',{name:"un",itemSpacing:1});un.fills=[];uf.appendChild(un);un.layoutSizingHorizontal="FILL";
const un1=figma.createText();un1.fontName={family:"Inter",style:"Semi Bold"};un1.characters="Carlos Eduardo";un1.fontSize=12.5;un1.fills=[{type:'SOLID',color:W}];un.appendChild(un1);
const un2=figma.createText();un2.fontName={family:"Inter",style:"Medium"};un2.characters="CEO · Id Seven";un2.fontSize=10;un2.fills=[{type:'SOLID',color:W,opacity:0.5}];un.appendChild(un2);
uf.appendChild(icon(I.chev,"#7E9AA0",16));

/* HEADER */
const hd=figma.createFrame();hd.name="header";hd.resize(1672,60);hd.layoutMode="HORIZONTAL";hd.primaryAxisSizingMode="FIXED";hd.counterAxisSizingMode="FIXED";hd.primaryAxisAlignItems="SPACE_BETWEEN";hd.counterAxisAlignItems="CENTER";hd.paddingLeft=24;hd.paddingRight=24;hd.itemSpacing=20;hd.fills=[{type:'SOLID',color:{r:0.949,g:0.965,b:0.980}}];hd.strokes=[{type:'SOLID',color:LINE}];hd.strokeAlign="INSIDE";hd.strokeTopWeight=0;hd.strokeLeftWeight=0;hd.strokeRightWeight=0;hd.strokeBottomWeight=1;A.appendChild(hd);hd.x=248;hd.y=0;
const ctx=figma.createAutoLayout('VERTICAL',{name:"context",itemSpacing:2});ctx.fills=[];hd.appendChild(ctx);
const t1=figma.createText();t1.fontName={family:"Inter",style:"Bold"};t1.characters="Meu quadro";t1.fontSize=16.5;t1.letterSpacing={unit:'PERCENT',value:-1};t1.fills=[{type:'SOLID',color:INK}];ctx.appendChild(t1);
const t2=figma.createText();t2.fontName={family:"Inter",style:"Medium"};t2.characters="Fluxo operacional · 2 tarefas ativas";t2.fontSize=11.5;t2.fills=[{type:'SOLID',color:INK3}];ctx.appendChild(t2);
const seg=figma.createAutoLayout('HORIZONTAL',{name:"viewtabs",itemSpacing:2});seg.paddingTop=3;seg.paddingBottom=3;seg.paddingLeft=3;seg.paddingRight=3;seg.cornerRadius=10;seg.fills=[{type:'SOLID',color:S0}];seg.counterAxisAlignItems="CENTER";hd.appendChild(seg);
function tab(label,active){const p=figma.createAutoLayout('HORIZONTAL',{name:"tab/"+label});p.paddingTop=6;p.paddingBottom=6;p.paddingLeft=14;p.paddingRight=14;p.cornerRadius=8;p.primaryAxisAlignItems="CENTER";p.counterAxisAlignItems="CENTER";p.fills=active?[{type:'SOLID',color:W}]:[];if(active)p.effects=[{type:'DROP_SHADOW',color:{r:0.059,g:0.165,b:0.235,a:0.10},offset:{x:0,y:1},radius:2,spread:0,visible:true,blendMode:'NORMAL'}];const t=figma.createText();t.fontName={family:"Inter",style:active?"Semi Bold":"Medium"};t.characters=label;t.fontSize=12.5;t.fills=[{type:'SOLID',color:active?INK:INK3}];p.appendChild(t);seg.appendChild(p);}
tab("Quadro",true);tab("Timeline",false);tab("Lista",false);
const rg=figma.createAutoLayout('HORIZONTAL',{name:"actions",itemSpacing:12});rg.fills=[];rg.counterAxisAlignItems="CENTER";hd.appendChild(rg);
const sf=figma.createAutoLayout('HORIZONTAL',{name:"search",itemSpacing:9});sf.paddingLeft=12;sf.paddingRight=12;sf.cornerRadius=9;sf.counterAxisAlignItems="CENTER";sf.fills=[{type:'SOLID',color:W}];sf.strokes=[{type:'SOLID',color:LINE}];sf.resize(230,36);sf.primaryAxisSizingMode="FIXED";sf.counterAxisSizingMode="FIXED";rg.appendChild(sf);
sf.appendChild(icon(I.search,"#7B879D",16));const spf=figma.createText();spf.fontName={family:"Inter",style:"Regular"};spf.characters="Buscar tarefas, clientes…";spf.fontSize=12.5;spf.fills=[{type:'SOLID',color:INK3}];sf.appendChild(spf);
const bell=figma.createAutoLayout('HORIZONTAL',{name:"notif"});bell.resize(36,36);bell.cornerRadius=9;bell.primaryAxisAlignItems="CENTER";bell.counterAxisAlignItems="CENTER";bell.fills=[{type:'SOLID',color:W}];bell.strokes=[{type:'SOLID',color:LINE}];rg.appendChild(bell);bell.appendChild(icon(I.bell,"#42506B",18));
const av0=figma.createAutoLayout('HORIZONTAL',{name:"avatar"});av0.resize(34,34);av0.cornerRadius=17;av0.primaryAxisAlignItems="CENTER";av0.counterAxisAlignItems="CENTER";av0.fills=[{type:'SOLID',color:TEAL}];rg.appendChild(av0);const ai0=figma.createText();ai0.fontName={family:"Inter",style:"Bold"};ai0.characters="CE";ai0.fontSize=11;ai0.fills=[{type:'SOLID',color:W}];av0.appendChild(ai0);

/* KPI STRIP (view controls + inline KPIs; NO right rail — board dominant) */
const cb=figma.createFrame();cb.name="kpi-strip";cb.resize(1672,52);cb.layoutMode="HORIZONTAL";cb.primaryAxisSizingMode="FIXED";cb.counterAxisSizingMode="FIXED";cb.primaryAxisAlignItems="SPACE_BETWEEN";cb.counterAxisAlignItems="CENTER";cb.paddingLeft=24;cb.paddingRight=24;cb.fills=[];A.appendChild(cb);cb.x=248;cb.y=60;
const cbl=figma.createAutoLayout('HORIZONTAL',{name:"cbl",itemSpacing:10});cbl.fills=[];cbl.counterAxisAlignItems="CENTER";cb.appendChild(cbl);
function chip(build){const c=figma.createAutoLayout('HORIZONTAL',{name:"chip",itemSpacing:7});c.paddingTop=6;c.paddingBottom=6;c.paddingLeft=9;c.paddingRight=10;c.cornerRadius=9;c.counterAxisAlignItems="CENTER";c.fills=[{type:'SOLID',color:W}];c.strokes=[{type:'SOLID',color:LINE}];cbl.appendChild(c);build(c);return c;}
chip(c=>{const a=figma.createAutoLayout('HORIZONTAL');a.resize(20,20);a.cornerRadius=10;a.primaryAxisAlignItems="CENTER";a.counterAxisAlignItems="CENTER";a.fills=[{type:'SOLID',color:TEAL}];c.appendChild(a);const at=figma.createText();at.fontName={family:"Inter",style:"Bold"};at.characters="CE";at.fontSize=8.5;at.fills=[{type:'SOLID',color:W}];a.appendChild(at);const tx=figma.createText();tx.fontName={family:"Inter",style:"Medium"};tx.characters="Carlos Eduardo";tx.fontSize=12;tx.fills=[{type:'SOLID',color:INK2}];c.appendChild(tx);c.appendChild(icon(I.chev,"#7B879D",14));});
chip(c=>{c.appendChild(icon(I.sliders,"#42506B",15));const tx=figma.createText();tx.fontName={family:"Inter",style:"Medium"};tx.characters="Filtros";tx.fontSize=12;tx.fills=[{type:'SOLID',color:INK2}];c.appendChild(tx);});
const kpis=figma.createAutoLayout('HORIZONTAL',{name:"kpis",itemSpacing:8});kpis.fills=[];kpis.counterAxisAlignItems="CENTER";cb.appendChild(kpis);
function kpi(label,val,color){const k=figma.createAutoLayout('HORIZONTAL',{name:"kpi",itemSpacing:6});k.paddingTop=6;k.paddingBottom=6;k.paddingLeft=10;k.paddingRight=11;k.cornerRadius=9;k.counterAxisAlignItems="CENTER";k.fills=[{type:'SOLID',color:W}];k.strokes=[{type:'SOLID',color:LINE}];const d=figma.createEllipse();d.resize(7,7);d.fills=[{type:'SOLID',color:color}];k.appendChild(d);const v=figma.createText();v.fontName={family:"Inter",style:"Bold"};v.characters=val;v.fontSize=12.5;v.fills=[{type:'SOLID',color:INK}];k.appendChild(v);const l=figma.createText();l.fontName={family:"Inter",style:"Medium"};l.characters=label;l.fontSize=11.5;l.fills=[{type:'SOLID',color:INK3}];k.appendChild(l);kpis.appendChild(k);}
kpi("Total","2",INK3);kpi("Em andamento","1",DOING);kpi("A fazer","1",TODO);
const slap=figma.createAutoLayout('HORIZONTAL',{name:"slapill",itemSpacing:6});slap.paddingTop=6;slap.paddingBottom=6;slap.paddingLeft=10;slap.paddingRight=11;slap.cornerRadius=9;slap.counterAxisAlignItems="CENTER";slap.fills=[{type:'SOLID',color:TEALBG}];kpis.appendChild(slap);const sdd=figma.createEllipse();sdd.resize(7,7);sdd.fills=[{type:'SOLID',color:GREEN}];slap.appendChild(sdd);const slt=figma.createText();slt.fontName={family:"Inter",style:"Semi Bold"};slt.characters="SLA no prazo";slt.fontSize=11.5;slt.fills=[{type:'SOLID',color:TEALD}];slap.appendChild(slt);

/* BOARD (dominant, full width, Card A) */
function makeTodoCardA(){const c=figma.createAutoLayout('VERTICAL',{name:"card/todo",itemSpacing:8});c.paddingTop=13;c.paddingBottom=13;c.paddingLeft=15;c.paddingRight=14;c.cornerRadius=12;c.fills=[{type:'SOLID',color:W}];c.strokes=[{type:'SOLID',color:LINE}];c.effects=[{type:'DROP_SHADOW',color:{r:0.059,g:0.165,b:0.235,a:0.06},offset:{x:0,y:1},radius:2,spread:0,visible:true,blendMode:'NORMAL'}];
 const eye=figma.createText();eye.fontName={family:"Inter",style:"Semi Bold"};eye.characters="SUNSET WEAR";eye.fontSize=9;eye.letterSpacing={unit:'PERCENT',value:8};eye.fills=[{type:'SOLID',color:INK3}];c.appendChild(eye);
 const ti=figma.createText();ti.fontName={family:"Inter",style:"Bold"};ti.characters="Reels de lançamento";ti.fontSize=14;ti.lineHeight={unit:'PERCENT',value:128};ti.fills=[{type:'SOLID',color:INK}];c.appendChild(ti);ti.layoutSizingHorizontal="FILL";
 const foot=figma.createAutoLayout('HORIZONTAL',{name:"foot",itemSpacing:8});foot.fills=[];foot.counterAxisAlignItems="CENTER";c.appendChild(foot);foot.layoutSizingHorizontal="FILL";foot.primaryAxisAlignItems="SPACE_BETWEEN";
 const meta=figma.createText();meta.fontName={family:"Inter",style:"Medium"};meta.characters="vence 26/08";meta.fontSize=11;meta.fills=[{type:'SOLID',color:INK3}];foot.appendChild(meta);
 const av=figma.createAutoLayout('HORIZONTAL');av.resize(22,22);av.cornerRadius=11;av.primaryAxisAlignItems="CENTER";av.counterAxisAlignItems="CENTER";av.fills=[{type:'SOLID',color:TEAL}];foot.appendChild(av);const ai=figma.createText();ai.fontName={family:"Inter",style:"Bold"};ai.characters="CE";ai.fontSize=9;ai.fills=[{type:'SOLID',color:W}];av.appendChild(ai);
 const bar=figma.createRectangle();bar.resize(3,50);bar.fills=[{type:'SOLID',color:TODO}];bar.topLeftRadius=12;bar.bottomLeftRadius=12;c.appendChild(bar);bar.layoutPositioning="ABSOLUTE";bar.constraints={horizontal:"MIN",vertical:"STRETCH"};bar.x=0;bar.y=0;return c;}
function makeEmpty(){const e=figma.createAutoLayout('VERTICAL',{name:"empty",itemSpacing:7});e.primaryAxisAlignItems="CENTER";e.counterAxisAlignItems="CENTER";e.paddingTop=30;e.paddingBottom=30;e.paddingLeft=12;e.paddingRight=12;e.cornerRadius=11;e.fills=[];e.strokes=[{type:'SOLID',color:{r:0.820,g:0.855,b:0.898}}];e.dashPattern=[5,5];e.appendChild(icon(I.inbox,"#9AA6B8",22));const q1=figma.createText();q1.fontName={family:"Inter",style:"Semi Bold"};q1.characters="Sem tarefas";q1.fontSize=11.5;q1.fills=[{type:'SOLID',color:INK3}];e.appendChild(q1);const q2=figma.createText();q2.fontName={family:"Inter",style:"Medium"};q2.characters="Arraste ou crie aqui";q2.fontSize=10;q2.fills=[{type:'SOLID',color:{r:0.6,g:0.65,b:0.72}}];e.appendChild(q2);return e;}
const well=figma.createFrame();well.name="board";well.layoutMode="HORIZONTAL";well.itemSpacing=14;well.paddingTop=16;well.paddingBottom=16;well.paddingLeft=16;well.paddingRight=16;well.cornerRadius=16;well.fills=[{type:'SOLID',color:S3}];A.appendChild(well);well.x=268;well.y=128;well.resize(1632,540);well.primaryAxisSizingMode="FIXED";well.counterAxisSizingMode="AUTO";well.counterAxisAlignItems="STRETCH";
const stages=[{n:"A Fazer",c:TODO,k:1,t:"todo"},{n:"Em andamento",c:DOING,k:1,t:"doing"},{n:"Revisão",c:REVIEW,k:0,t:"empty"},{n:"Finalizado",c:DONE,k:0,t:"empty"}];
for(const s of stages){
 const col=figma.createAutoLayout('VERTICAL',{name:"col/"+s.n,itemSpacing:10});col.paddingTop=12;col.paddingBottom=14;col.paddingLeft=11;col.paddingRight=11;col.cornerRadius=14;col.fills=[{type:'SOLID',color:S4}];well.appendChild(col);col.layoutSizingHorizontal="FILL";col.minHeight=508;
 const h=figma.createAutoLayout('HORIZONTAL',{name:"colhead"});h.fills=[];h.counterAxisAlignItems="CENTER";h.primaryAxisAlignItems="SPACE_BETWEEN";h.paddingLeft=4;h.paddingRight=2;h.paddingTop=2;h.paddingBottom=4;col.appendChild(h);h.layoutSizingHorizontal="FILL";
 const hl=figma.createAutoLayout('HORIZONTAL',{name:"hl",itemSpacing:8});hl.fills=[];hl.counterAxisAlignItems="CENTER";h.appendChild(hl);const dot=figma.createEllipse();dot.resize(8,8);dot.fills=[{type:'SOLID',color:s.c}];hl.appendChild(dot);const ht=figma.createText();ht.fontName={family:"Inter",style:"Semi Bold"};ht.characters=s.n;ht.fontSize=12.5;ht.fills=[{type:'SOLID',color:INK}];hl.appendChild(ht);
 const cpp=figma.createAutoLayout('HORIZONTAL');cpp.paddingLeft=7;cpp.paddingRight=7;cpp.paddingTop=2;cpp.paddingBottom=2;cpp.cornerRadius=8;cpp.fills=[{type:'SOLID',color:S0}];cpp.counterAxisAlignItems="CENTER";h.appendChild(cpp);const cptx=figma.createText();cptx.fontName={family:"Inter",style:"Bold"};cptx.characters=String(s.k);cptx.fontSize=10.5;cptx.fills=[{type:'SOLID',color:INK3}];cpp.appendChild(cptx);
 if(s.t==="doing"){const inst=cardA.createInstance();col.appendChild(inst);inst.layoutSizingHorizontal="FILL";}
 else if(s.t==="todo"){const cd=makeTodoCardA();col.appendChild(cd);cd.layoutSizingHorizontal="FILL";}
 else{const es=makeEmpty();col.appendChild(es);es.layoutSizingHorizontal="FILL";}
 const add=figma.createAutoLayout('HORIZONTAL',{name:"add",itemSpacing:6});add.counterAxisAlignItems="CENTER";add.paddingTop=7;add.paddingBottom=7;add.paddingLeft=8;add.paddingRight=8;add.cornerRadius=8;add.fills=[];col.appendChild(add);add.layoutSizingHorizontal="FILL";add.appendChild(icon(I.plus,"#7B879D",15));const at=figma.createText();at.fontName={family:"Inter",style:"Medium"};at.characters="Adicionar tarefa";at.fontSize=11.5;at.fills=[{type:'SOLID',color:INK3}];add.appendChild(at);
}
return { A:A.id, sidebar:sb.id, board:well.id, ok:true };
